Enhance country images download workflow
Updated the workflow to download images for all 250 countries and territories, including specific handling for Kosovo (XK).

diff --git a/.github/workflows/country-images.yml b/.github/workflows/country-images.yml
--- a/.github/workflows/country-images.yml
+++ b/.github/workflows/country-images.yml
@@ -1,4 +1,4 @@
-name: Download country images
+name: Download 250 country images
 
 on:
   workflow_dispatch:
@@ -14,22 +14,46 @@ jobs:
       - name: Get repository
         uses: actions/checkout@v4
 
-      - name: Download country flags
+      - name: Download all country images
         run: |
           mkdir -p public/images/countries
 
-          countries="af al dz ad ao ag ar am au at az bs bh bd bb by be bz bj bt bo ba bw br bn bg bf bi cv kh cm ca cf td cl cn co km cg cd cr ci hr cu cy cz dk dj dm do ec eg sv gq er ee sz et fj fi fr ga gm ge de gh gr gd gt gn gw gy ht hn hu is in id ir iq ie il it jm jp jo kz ke ki kp kr kw kg la lv lb ls lr ly li lt lu mg mw my mv ml mt mh mr mu mx fm md mc mn me ma mz mm na nr np nl nz ni ne ng mk no om pk pw pa pg py pe ph pl pt qa ro ru rw kn lc vc ws sm st sa sn rs sc sl sg sk si sb so za ss es lk sd sr se ch sy tj tz th tl tg to tt tn tr tm tv ug ua ae gb us uy uz vu va ve vn ye zm zw"
+          codes="
+          AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ
+          BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO VG BN BG BF BI
+          CV KH CM CA KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CY CZ
+          DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE
+          GH GI GR GL GD GP GU GT GG GN GW GY HT HM HN HK HU IS IN ID IR IQ IE IL IM IT
+          JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU
+          MO MG MW MY MV ML MT MH MQ MR MU MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MK NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW
+          BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SE CH SY TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VA VE VN VG WF EH YE ZM ZW
+          XK
+          "
 
-          for code in $countries; do
-            curl -L --fail \
-              "https://flagcdn.com/w640/${code}.png" \
-              -o "public/images/countries/${code^^}.png"
+          for code in $codes; do
+            CODE=$(echo "$code" | tr '[:lower:]' '[:upper:]')
+
+            if [ "$CODE" = "XK" ]; then
+              URL="https://flagcdn.com/w640/xk.png"
+            else
+              URL="https://flagcdn.com/w640/$(echo "$CODE" | tr '[:upper:]' '[:lower:]').png"
+            fi
+
+            echo "Downloading $CODE..."
+            curl -L --fail --silent --show-error \
+              "$URL" \
+              -o "public/images/countries/${CODE}.png" \
+              || echo "Could not download $CODE"
           done
 
-      - name: Save images to GitHub
+      - name: Save images
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
           git add public/images/countries
-          git commit -m "Add country images" || echo "Nothing to commit"
+
+          git commit -m "Add images for all 250 countries and territories" \
+            || echo "Nothing new to commit"
+
           git push
